### ISSUE TITLE
Show array/tables in result

### ISSUE THREAD

**Issue by oori** [RPing/influx-prompt#1]
Great software, thanks.  To make this more useable, we're missing something that returns an array/table, not just a list in the results output.
For example: Group by tag, ```GROUP BY time(1h), "tag"``` or ```SHOW CONTINUOUS QUERIES```.

Thanks.

**Comment by RPing** [comment]
Multiple series showed by `GROUP BY` should be fixed by #9 , which shipped on `0.1.2`.

**Comment by RPing** [comment]
ref #10

**Comment by RPing** [comment]
All bugs fixed in [1.0.0](https://github.com/RPing/influx-prompt/releases/tag/1.0.0).
Feel free to open a new issue if you encounter any problem.
