### ISSUE TITLE
Upgrading to prompt_toolkit 2.0/3.0

### ISSUE THREAD

**Issue by RPing** [RPing/influx-prompt#12]
`Prompt_toolkit 2.0 is not compatible with 1.0.`
https://python-prompt-toolkit.readthedocs.io/en/master/pages/upgrading/2.0.html
https://python-prompt-toolkit.readthedocs.io/en/master/pages/upgrading/3.0.html

**Comment by 404cn** [comment]
yes, please.

Or I can just use one of the influx-prompt and mycli
