### ISSUE TITLE
Meet some bugs

### ISSUE THREAD

**Issue by SimonHu-HN** [RPing/influx-prompt#7]
Hello, your tool is pretty cool but I find some bugs when I execute the 

`SELECT MEAN("index") FROM "h2o_quality" GROUP BY location,randtag (*)`

which is a example sentence in the official documentation.

However, the original CLI will display like below after I run (*)
`
name: h2o_quality
tags: location=coyote_creek, randtag=1
time                  mean
----                  ----
1970-01-01T00:00:00Z  50.69033760186263

name: h2o_quality
tags: location=coyote_creek, randtag=2
time                   mean
----                   ----
1970-01-01T00:00:00Z   49.661867544220485

name: h2o_quality
tags: location=coyote_creek, randtag=3
time                   mean
----                   ----

[................]`

But in influx-prompt, it will give the unfiltered messy data, such as:

`
h2o_temperature,location=coyote_creek degrees=61 1440383040

h2o_temperature,location=coyote_creek degrees=63 1440383400

h2o_temperature,location=coyote_creek degrees=67 1440383760

h2o_temperature,location=coyote_creek degrees=61 1440384120

h2o_temperature,location=coyote_creek degrees=61 1440384480

h2o_temperature,location=coyote_creek degrees=65 1440384840

h2o_temperature,location=coyote_creek degrees=62 1440385200

h2o_temperature,location=coyote_creek degrees=63 1440385560

`

Just like push all of the data in the database to me.

Have you ever meet such issue?

My influxdb is 1.7.

Thanks in advance.

**Comment by RPing** [comment]
Can you provide more details about how to reproduce it? My test result is different from yours.
But it indeed has some bugs. ref #8

**Comment by SimonHu-HN** [comment]
Maybe it is a bug to the MobaXterm SSH terminal. Not your fault...💀💀💀

**Comment by RPing** [comment]
That's fine. Feel free to report the issue if you encounter again :)
